### ISSUE TITLE
Error when starting server

### ISSUE THREAD

**Issue by Qoraiche** [godka/kurento-rtmp#5]
Why i get this error when starting server (I follow your build instructions from Readme)
```
/home/ubuntu/workspace/kurento-rtmp/node_modules/node-media-server/api/controllers/server.js:72
async function getInfo(req, res, next) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/workspace/kurento-rtmp/node_modules/node-media-server/api/routes/server.js:3:26)
```

**Comment by godka** [comment]
perhaps there are some bugs on the newest node-media-server,please contact

**Comment by godka** [comment]
perhaps there are some bugs on the newest node-media-server,please contact
https://github.com/illuspas/Node-Media-Server
Surely,you can use another popular rtmp-servers to test this repo,such as nginx-rtmp-module,srs ,by deleting these lines.
https://github.com/godka/kurento-rtmp/blob/b87a137fea9e2c305c5b5e17f2b77272d122a755/server.js#L439

**Comment by Qoraiche** [comment]
Hi @godka, 
first, thanks for your help
But your solution doesn't work for me :
the same error happens when I delete new NodeMediaServer lines. I try to remove the full NodeMediaServer package and update but I get NodeMediaServer module not found when start server, I 've outside VPS ubuntu running nginx with rtmp-module receiving RTMP just fine, so i want to use your kurento-rtmp as a webrtc client to send streaming , how i can achieve this?.

thanks again.

**Comment by godka** [comment]
sorry,I mean if u only have sth wrong on node-media-server,you can just delete this module,because it's just a rtmp-server which is written in node-js.you can use another different rtmp-server such as srs,nginx-rtmp-module,etc.
you can delete these lines if u wanna delete node-media-server module and use your own rtmp-server.
https://github.com/godka/kurento-rtmp/blob/b87a137fea9e2c305c5b5e17f2b77272d122a755/server.js#L17
https://github.com/godka/kurento-rtmp/blob/b87a137fea9e2c305c5b5e17f2b77272d122a755/server.js#L439
https://github.com/godka/kurento-rtmp/blob/b87a137fea9e2c305c5b5e17f2b77272d122a755/server.js#L440
